Simplifying bash code

diff --git a/.github/workflows/validate_pr_labels_and_release_notes.yml b/.github/workflows/validate_pr_labels_and_release_notes.yml
--- a/.github/workflows/validate_pr_labels_and_release_notes.yml
+++ b/.github/workflows/validate_pr_labels_and_release_notes.yml
@@ -47,7 +47,6 @@ jobs:
           echo "Allowed labels: ${ALLOWED_LABELS_ARRAY[@]}"
           echo "PR labels: ${PR_LABELS_ARRAY[@]}"
           
-          SHOULD_FAIL_JOB="false"
           ERROR_MESSAGE=""
 
           RED='\033[0;31m'
@@ -55,22 +54,20 @@ jobs:
 
           # Check if PR has any labels
           if [ ${#PR_LABELS_ARRAY[@]} -eq 0 ]; then
-            FORMATTED_LABELS=$(printf "'%s', " "${ALLOWED_LABELS_ARRAY[@]}" | sed 's/, $//')
-            echo -e "${RED}Error: Pull request must have at least one label from the following list: ${ALLOWED_LABELS_ARRAY[@]}${NC}"
             ERROR_MESSAGE="This pull request does not contain a valid label. Please add one of the following labels: [${FORMATTED_LABELS}]"
             echo "error_message=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
             exit 1
           fi
-          
+
           # Validate labels exist in allowed list
           for LABEL in "${PR_LABELS_ARRAY[@]}"; do
             if [[ ! " ${ALLOWED_LABELS_ARRAY[@]} " =~ " ${LABEL} " ]]; then
-              echo -e "${RED}Invalid label found: $LABEL${NC}"
-              SHOULD_FAIL_JOB="true"
               ERROR_MESSAGE="This pull request contains invalid label: '${LABEL}'. Please use one of the following labels: [${FORMATTED_LABELS}]"
+              echo "error_message=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
+              exit 1
             fi
           done
-          
+
           # Validate release notes
           for LABEL in "${ALLOWED_LABELS_ARRAY[@]}"; do
             LABEL=$(echo "$LABEL" | sed 's/^ *//g' | sed 's/ *$//g')
@@ -81,13 +78,13 @@ jobs:
               cmd="awk '/<$LABEL>.*<\/$LABEL>/'"
               FEATURE_RELEASE_NOTE="$(echo $PR_BODY | eval $cmd)"
               if [[ -z "$FEATURE_RELEASE_NOTE" ]]; then
-                 echo -e "${RED}Pull requests labeled with '$LABEL' must have the release note in the pull request body in the following format '<$LABEL> {THE RELEASE NOTE}  </$LABEL>'${NC}"
-                 SHOULD_FAIL_JOB="true"
-                 ERROR_MESSAGE="${ERROR_MESSAGE}"$'\n'"Pull requests labeled with '${LABEL}' must have the release note in the pull request body in the following format '<${LABEL}> {THE RELEASE NOTE} </${LABEL}>'"
+                 ERROR_MESSAGE="Pull requests labeled with '${LABEL}' must have the release note in the pull request body in the following format '<${LABEL}> {THE RELEASE NOTE} </${LABEL}>'"
+                 echo "error_message=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
+                 exit 1
               fi
             fi
           done
-          
+
           if [[ "$SHOULD_FAIL_JOB" == "true" ]]; then
             echo "error_message=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
             exit 1
